[pytest]
# Default execution arguments
# -n auto: Detect CPU cores and use them for parallel execution (Removed to fix IDE discovery)
# --alluredir: Path for Allure results
addopts = -v --alluredir=reports --clean-alluredir

# Directory discovery
testpaths = applications/web/demo/tests

# Logging configuration
log_cli = false
log_cli_level = INFO
log_cli_format = %(asctime)s [%(levelname)s] %(name)s - %(message)s
log_cli_date_format = %Y-%m-%d %H:%M:%S

filterwarnings =
    ignore::urllib3.exceptions.InsecureRequestWarning
