# QA Environment configuration for busisness_partners_portal
web:
  base_url: "https://testbusinesspartners.nationalindemnity.com"
  timeout: 10

credentials:
  microsoft:
    email: "cGl0YW1haWxib3grbmljby5ob0BnbWFpbC5jb20="
    password: "QmVya3NoaXJlOTk="
  okta:
    bypass: true
    code: ""
