# QA Environment configuration for busisness_partners_portal
web:
  base_url: "https://testportal.bhhomestate.com"
  timeout: 10
  default_agency: "Berkshire Hathaway Homestate CompaniesOmahaNE"

credentials:
  microsoft:
    email: "am1yb3NhYmFsQG5hdGlvbmFsaW5kZW1uaXR5LmNvbQ=="
    password: "Kioq"
  okta:
    bypass: false
    code: ""
