# QA Environment configuration for pc_agency_portal
web:
  base_url: "https://testportal.bhhomestate.com"
  timeout: 10

credentials:
  microsoft:
    email: "jmrosabal@nationalindemnity.com"
    password: "***"
  okta:
    code: ""
